In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('UDISE_2023-24_Table_2.1.csv')

In [3]:
df.columns = df.columns.str.replace(" ", "_")
df.columns = df.columns.str.replace("-", "_")
df.columns = df.columns.str.lower()
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.options.display.float_format = '{:,.2f}'.format

In [4]:
df.head()

,sl._no.,india/state/ut,total_number_of___schools,total_number_of___enrolments,total_number_of___teachers,percentage_share_of_schools_by_category___primary,percentage_share_of_schools_by_category___upper_primary,percentage_share_of_schools_by_category___secondary,percentage_share_of_schools_by_category___higher_secondary,percentage_share_of_enrolments_by_level____primary_,percentage_share_of_enrolments_by_level____upper_primary_,percentage_share_of_enrolments_by_level___secondary,percentage_share_of_enrolments_by_level___higher_secondary,percentage_share_of_teachers_by_school_category___primary,percentage_share_of_teachers_by_school_category___upper_primary,percentage_share_of_teachers_by_school_category___secondary,percentage_share_of_teachers_by_school_category___higher_secondary
0,1,India,1471891,248045828,9807600,50.00,29.40,9.80,10.80,48.70,25.40,14.90,10.90,24.00,28.60,16.20,31.10
1,2,Andaman and Nicobar Islands,412,72119,5750,50.70,19.20,13.10,17.00,46.10,23.60,15.90,14.40,17.30,16.90,17.50,48.30
2,3,Andhra Pradesh,61373,8741885,338293,61.50,13.50,18.90,6.10,46.10,25.70,16.50,11.60,28.60,14.00,42.70,14.70
3,4,Arunachal Pradesh,3490,323717,24700,48.60,36.80,9.50,5.20,53.70,24.00,13.40,8.90,19.10,42.60,20.60,17.60
4,5,Assam,56630,6922533,342199,66.20,16.70,12.50,4.70,53.40,25.10,14.30,7.20,32.60,20.50,29.10,17.80

In [5]:
df.tail(5)

,sl._no.,india/state/ut,total_number_of___schools,total_number_of___enrolments,total_number_of___teachers,percentage_share_of_schools_by_category___primary,percentage_share_of_schools_by_category___upper_primary,percentage_share_of_schools_by_category___secondary,percentage_share_of_schools_by_category___higher_secondary,percentage_share_of_enrolments_by_level____primary_,percentage_share_of_enrolments_by_level____upper_primary_,percentage_share_of_enrolments_by_level___secondary,percentage_share_of_enrolments_by_level___higher_secondary,percentage_share_of_teachers_by_school_category___primary,percentage_share_of_teachers_by_school_category___upper_primary,percentage_share_of_teachers_by_school_category___secondary,percentage_share_of_teachers_by_school_category___higher_secondary
32,33,Telangana,42901,7293644,341460,47.90,17.40,27.00,7.70,47.80,25.20,15.30,11.80,14.30,16.00,52.70,16.90
33,34,Tripura,4923,689408,37661,50.20,25.30,13.60,10.80,48.40,25.20,14.60,11.80,20.50,20.00,21.80,37.60
34,35,Uttar Pradesh,255087,41662794,1538479,52.30,34.00,4.70,9.00,49.40,25.40,13.70,11.50,36.60,34.10,5.60,23.70
35,36,Uttarakhand,22551,2372400,130741,57.30,24.40,6.20,12.00,47.70,24.20,15.00,13.10,23.70,25.20,8.80,42.30
36,37,West Bengal,93945,18015525,576557,79.30,9.20,3.50,8.10,47.00,24.50,17.00,11.50,52.20,6.70,6.50,34.60

In [6]:
df.shape

(37, 17)

In [7]:
df.columns

Index(['sl._no.', 'india/state/ut', 'total_number_of___schools',
       'total_number_of___enrolments', 'total_number_of___teachers',
       'percentage_share_of_schools_by_category___primary',
       'percentage_share_of_schools_by_category___upper_primary',
       'percentage_share_of_schools_by_category___secondary',
       'percentage_share_of_schools_by_category___higher_secondary',
       'percentage_share_of_enrolments_by_level____primary_',
       'percentage_share_of_enrolments_by_level____upper_primary_',
       'percentage_share_of_enrolments_by_level___secondary',
       'percentage_share_of_enrolments_by_level___higher_secondary',
       'percentage_share_of_teachers_by_school_category___primary',
       'percentage_share_of_teachers_by_school_category___upper_primary',
       'percentage_share_of_teachers_by_school_category___secondary',
       'percentage_share_of_teachers_by_school_category___higher_secondary'],
      dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 17 columns):
 #   Column                                                              Non-Null Count  Dtype
---  ------                                                              --------------  -----
 0   sl._no.                                                             37 non-null     int64
 1   india/state/ut                                                      37 non-null     str
 2   total_number_of___schools                                           37 non-null     int64
 3   total_number_of___enrolments                                        37 non-null     int64
 4   total_number_of___teachers                                          37 non-null     int64
 5   percentage_share_of_schools_by_category___primary                   37 non-null     float64
 6   percentage_share_of_schools_by_category___upper_primary             37 non-null     float64
 7   percentage_share_of_schools_by_category___secondary                 37 non-null     float64
 8   percentage_share_of_schools_by_category___higher_secondary          37 non-null     float64
 9   percentage_share_of_enrolments_by_level____primary_                 37 non-null     float64
 10  percentage_share_of_enrolments_by_level____upper_primary_           37 non-null     float64
 11  percentage_share_of_enrolments_by_level___secondary                 37 non-null     float64
 12  percentage_share_of_enrolments_by_level___higher_secondary          37 non-null     float64
 13  percentage_share_of_teachers_by_school_category___primary           37 non-null     float64
 14  percentage_share_of_teachers_by_school_category___upper_primary     37 non-null     float64
 15  percentage_share_of_teachers_by_school_category___secondary         37 non-null     float64
 16  percentage_share_of_teachers_by_school_category___higher_secondary  37 non-null     float64
dtypes: float64(12), int64(4), str(1)
memory usage: 5.0 KB

In [9]:
df.sort_values(by=['total_number_of___schools', 'total_number_of___teachers'], ascending=False).head(5)

,sl._no.,india/state/ut,total_number_of___schools,total_number_of___enrolments,total_number_of___teachers,percentage_share_of_schools_by_category___primary,percentage_share_of_schools_by_category___upper_primary,percentage_share_of_schools_by_category___secondary,percentage_share_of_schools_by_category___higher_secondary,percentage_share_of_enrolments_by_level____primary_,percentage_share_of_enrolments_by_level____upper_primary_,percentage_share_of_enrolments_by_level___secondary,percentage_share_of_enrolments_by_level___higher_secondary,percentage_share_of_teachers_by_school_category___primary,percentage_share_of_teachers_by_school_category___upper_primary,percentage_share_of_teachers_by_school_category___secondary,percentage_share_of_teachers_by_school_category___higher_secondary
0,1,India,1471891,248045828,9807600,50.00,29.40,9.80,10.80,48.70,25.40,14.90,10.90,24.00,28.60,16.20,31.10
34,35,Uttar Pradesh,255087,41662794,1538479,52.30,34.00,4.70,9.00,49.40,25.40,13.70,11.50,36.60,34.10,5.60,23.70
20,21,Madhya Pradesh,123412,15361543,639525,49.40,35.70,6.70,8.20,51.20,25.90,13.90,9.00,21.20,37.90,11.60,29.40
21,22,Maharashtra,108237,21375970,738114,46.10,27.00,16.50,10.40,44.20,25.90,16.90,13.00,18.90,27.10,25.10,28.80
29,30,Rajasthan,107757,16786065,775745,35.00,32.00,6.80,26.10,49.60,24.70,14.50,11.20,10.80,28.80,9.20,51.20

In [10]:
df.describe()

,sl._no.,total_number_of___schools,total_number_of___enrolments,total_number_of___teachers,percentage_share_of_schools_by_category___primary,percentage_share_of_schools_by_category___upper_primary,percentage_share_of_schools_by_category___secondary,percentage_share_of_schools_by_category___higher_secondary,percentage_share_of_enrolments_by_level____primary_,percentage_share_of_enrolments_by_level____upper_primary_,percentage_share_of_enrolments_by_level___secondary,percentage_share_of_enrolments_by_level___higher_secondary,percentage_share_of_teachers_by_school_category___primary,percentage_share_of_teachers_by_school_category___upper_primary,percentage_share_of_teachers_by_school_category___secondary,percentage_share_of_teachers_by_school_category___higher_secondary
count,37.00,37.00,37.00,37.00,37.00,37.00,37.00,37.00,37.00,37.00,37.00,37.00,37.00,37.00,37.00,37.00
mean,19.00,"79,561.68","13,407,882.59","530,140.54",47.44,26.53,12.77,13.26,49.98,24.28,14.70,11.04,21.29,25.68,20.03,32.99
std,10.82,"240,765.83","40,577,601.04","1,598,759.42",12.64,10.95,7.43,9.89,4.46,1.94,1.48,2.43,9.21,13.77,12.91,16.90
min,1.00,37.00,"12,591.00",911.00,6.10,5.20,0.00,2.90,44.20,20.50,10.40,5.10,2.00,4.40,0.00,9.40
25%,10.00,"3,490.00","323,717.00","24,700.00",40.50,17.40,7.30,6.20,46.20,23.40,13.70,9.10,16.20,14.00,10.70,18.20
50%,19.00,"23,517.00","5,599,742.00","206,591.00",48.60,25.30,11.50,10.10,48.70,24.60,14.90,11.50,20.50,25.20,18.90,29.40
75%,28.00,"61,373.00","11,496,709.00","394,053.00",53.30,35.70,16.50,16.00,52.10,25.70,15.90,13.00,23.90,36.50,26.20,48.70
max,37.00,"1,471,891.00","248,045,828.00","9,807,600.00",79.30,50.40,30.40,45.20,63.90,27.60,17.30,15.80,52.20,56.10,53.20,71.50

In [11]:
df["total_number_of___enrolments"]

0     248045828
1         72119
2       8741885
3        323717
4       6922533
5      21348149
6        265706
7       5776548
8        141282
9       4506578
10       304735
11     11496709
12      5599742
13      1426412
14      2629949
15      7143255
16     11926303
17      6281704
18        56642
19        12591
20     15361543
21     21375970
22       647434
23      1052884
24       293763
25       412975
26      7756910
27       244828
28      5988681
29     16786065
30       121395
31     12993050
32      7293644
33       689408
34     41662794
35      2372400
36     18015525
Name: total_number_of___enrolments, dtype: int64

In [12]:
df[[
    "total_number_of___enrolments",
    "total_number_of___teachers",
    "total_number_of___schools"
]]

,total_number_of___enrolments,total_number_of___teachers,total_number_of___schools
0,248045828,9807600,1471891
1,72119,5750,412
2,8741885,338293,61373
3,323717,24700,3490
4,6922533,342199,56630
5,21348149,657063,94686
6,265706,10237,230
7,5776548,278798,56615
8,141282,4995,432
9,4506578,160479,5497
10,304735,14594,1487
11,11496709,394053,53626
12,5599742,250909,23517
13,1426412,101131,17826
14,2629949,167046,24296
15,7143255,206591,44475
16,11926303,433942,75869
17,6281704,291096,15864
18,56642,6432,995
19,12591,911,37
20,15361543,639525,123412
21,21375970,738114,108237
22,647434,40921,4646
23,1052884,55726,14601
24,293763,23013,3941
25,412975,32602,2725
26,7756910,335496,61693
27,244828,13202,735
28,5988681,273092,27404
29,16786065,775745,107757
30,121395,15489,1254
31,12993050,550558,58722
32,7293644,341460,42901
33,689408,37661,4923
34,41662794,1538479,255087
35,2372400,130741,22551
36,18015525,576557,93945

In [13]:
df.sort_values(
    by="total_number_of___enrolments",
    ascending=False
)[["total_number_of___teachers", "total_number_of___schools"]].head(10)

    total_number_of___teachers  total_number_of___schools
0                      9807600                    1471891
34                     1538479                     255087
21                      738114                     108237
5                       657063                      94686
36                      576557                      93945
29                      775745                     107757
20                      639525                     123412
31                      550558                      58722
16                      433942                      75869
11                      394053                      53626

In [ ]:
df.sort_values(
    by="total_number_of___enrolments",
    ascending=False
)[["percentage_share_of_schools_by_category___secondary", "percentage_share_of_schools_by_category___upper_primary"]].head(10)

In [ ]:
df[df["india/state/ut"] == "Uttar_Pradesh"]

In [ ]:
df[df["percentage_share_of_schools_by_category___secondary"] > 30][[
    "india/state/ut",
    "percentage_share_of_schools_by_category___upper_primary"
]]

In [ ]:
df["percentage_share_of_schools_by_category___secondary"]
df["percentage_share_of_schools_by_category___secondary"] > 2
df[df["percentage_share_of_schools_by_category___secondary"] > 2]

In [ ]:
df.query("total_number_of___schools > 2")

In [ ]:
df["percentage_share_of_schools_by_category___secondary"].mean()

In [ ]:
df["percentage_share_of_schools_by_category___secondary"].mean().round(2)

In [ ]:
df["percentage_share_of_schools_by_category___secondary"].median()

In [ ]:
df["percentage_share_of_schools_by_category___secondary"].min()

In [ ]:
df["percentage_share_of_schools_by_category___secondary"].max()

In [ ]:
df.total_number_of_enrolments_total.max()

In [ ]:
df.isna().sum().sort_values(ascending=False)

In [ ]:
df[df["total_number_of_schools_total"].isna()][[
    "percentage_share_of_schools_by_category___upper_primary",
    "percentage_share_of_schools_by_category_primary"
]]

In [ ]:
df[[
    "india/state/ut",
    "total_number_of___schools",
    "total_number_of___teachers"
]].sort_values(
    "total_number_of___schools",
    ascending=False
).head(10)

In [ ]:
df["total_number_of___schools"]
df["total_number_of___schools"]>2
df[df["total_number_of___schools"]>2]

In [ ]:
df["total_number_of___schools"].mean()

In [ ]:
df["total_number_of___teachers"].mean().round(2)

In [ ]:
df["total_number_of___teachers"].median()

In [ ]:
df["total_number_of___teachers"].min()

In [ ]:
df["total_number_of___teachers"].max()

In [ ]:
df.percentage_share_of_schools_by_category_primary.max()

In [ ]:
df.isna().sum().sort_values(ascending=False)

In [ ]:
df[[
    "india/state/ut",
    "total_number_of___enrolments",
    "total_number_of___teachers"
]].sort_values(
    "total_number_of___enrolments",
    ascending=False
).head(10)